starting project
luanarahal/raji-react pull request #1
Opened 2023-07-26 19:18 UTC by luanarahal

2023-07-31 13:34 UTC, antoniomatiolijr requested changes
Transforma em um projeto de React com typescript

2023-07-31 13:34 UTC, antoniomatiolijr commented on public/index.html
> +    <title>Treinamento React</title>
Atualiza o título para o real objetivo

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/App.css
> +}
Adicionar um enter no final do arquivo

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/App.js
> +import Paginainicial from './Pages/Paginainicial/Paginainicial'
Atualiza para ingles e substitui o arquivo do componente para index.js que ai vc vai conseguir importar só fazendo assim './Pages/PaginaInicial'

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Assets/logo/logo.png
Remover esse Arquivo

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/Cabecalho/Cabecalho.jsx
> +const Cabecalho = () => {
Ingles `Header`

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/Cabecalho/Cabecalho.module.css
> +.cabecalho {
classes tb devem ser em ingles

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/Cabecalho/Cabecalho.module.css
> +/*-----------------------------------------*/
remover e separar em outro componente de modal

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/CaixaConteudo/CaixaConteudo.jsx
> +export default CaixaConteudo
falta colocar em ingles, o enter no final do arquivo e ponto e virgula;

Acho melhor configurar o ESLint no projeto já de cara para envitar esses problemas

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/CaixaConteudo/CaixaConteudo.module.css
> + }
Enter no final do arquivo

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/Components/Menu/Menu.jsx
> +//STYLES
tira esses comentários

2023-07-31 13:34 UTC, antoniomatiolijr commented on src/reset.css
Remove esse arquivo, isso é bem estranho!

2023-08-03 12:18 UTC, luanarahal commented on src/Components/CaixaConteudo/CaixaConteudo.jsx
> +export default CaixaConteudo
ESLint configurado!

2023-08-03 16:36 UTC, luanarahal commented on src/App.js
> +import Paginainicial from './Pages/Paginainicial/Paginainicial'
alterei para inglês, mas não entendi muito bem o que é pra fazer em "substitui o arquivo do componente para index.js", é para eu renomear o arquivo App.js para index.js? Se for isso, o q eu faço com o arquivo index.js? Renomeio também?

2023-08-05 17:01 UTC, closed without merging